# This is a basic workflow to help you get started with Actions

name: Build 3.9

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:    
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python-version: [3.9]
            compiler: [ g++-10 ]
            include:
              - os: ubuntu-latest
                compiler: g++-10
                target: Linux
                python-version: 3.9
              - os: macos-latest
                compiler: g++-10
                target: Linux
                python-version: 3.9
              - os: windows-latest
                compiler: g++-10
                target: Linux
                python-version: 3.9

        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
          - name: Run build
            run: |

              python3 ./setup.py build
          - uses: actions/upload-artifact@v2
            with:
              name: Upload
              path: build # or path/to/artifact
